version: '2'
services:
  postgres:
    build: ./postgres
    image: ricardojob/banco
    ports:
     - "5433:5432"
     - "4849:4848"
  web:
    build: .
    image: ricardojob/app
    ports:
     - "8081:8080"
    links:
     - postgres:host-banco
